#oracle配置信息
server:
  tomcat:
    basedir: /data/apps/temp

#spring配置
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      location: /tmp
      max-file-size: 10MB
      max-request-size: 12MB
  data:
    mongodb:
      database: dist
      host: 127.0.0.1
      port: 27017
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 10000

#dubbo配置
dubbo:
  application:
    name: boot-order-service-consumer
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  scan:
    base-packages: com.transform.web
  protocol:
    port: 20881
  monitor:
    protocol: registry
  consumer:
    timeout: 30000

fastConfig:
  txtSavePath: D:\\picBed\\infoTable\\信息表.txt
  picSavePath: D:\\picBed\\fast\\
  resourceHandlerPath: uploadSub